### ISSUE TITLE
Provide a zipped file provider

### ISSUE THREAD

**Issue by Tratcher** [aspnet/FileSystem#292] opened 2017-09-06 19:57 UTC
Consider a file provider that exposes the contents of a zip file. There may also be optional caching of the unzipped content of individual files. This could be used to reduce project publish size, time, etc..

**Comment by natemcmaster** [comment] 2017-09-10 05:37
Duplicate of https://github.com/aspnet/FileSystem/issues/213. We discussed before and decided not to implement this. Any reason to reconsider?

**Comment by Tratcher** [comment] 2017-09-10 05:42
@DamianEdwards and I were discussing different ways to reduce app deployment size, and the static wwwroot assets are the one of the largest pieces. I put together a sample here:
https://github.com/Tratcher/ZipFileProviderExp/blob/729bff83b63022e7a666bb6c33e424a4e0afe9f7/SampleSite/Program.cs#L26
It reduced the template static assets size from 2.4mb to 600kb.

The actual solution he wants is to pre-gzip the individual files and serve them directly to the client with the proper compression headers, but all of that logic needs to be built into the StaticFiles middleware.

**Comment by muratg** [comment] 2017-11-16 00:23
Tentatively putting this in 2.2.0.  I suspect we'll possibly punt it again after talking about some details.

**Comment by aspnet-hello** [comment] 2018-01-01 23:53
This issue was moved to aspnet/Home#2541

**Closed by aspnet-hello** 2018-01-01 23:53 UTC
