### ISSUE TITLE
EmbeddedFileProvider doesn't handle - in folder names correctly

### ISSUE THREAD

**Issue by joeaudette** [aspnet/FileSystem#277] opened 2017-06-09 12:28 UTC
I'm using EmbeddedFileProvider in conjunction with StaticFilesMiddleware to serve some static resources.

I ran into a problem with some resources that have - in the folder path were returning not found. For example a request for /cr/js/ckeditor461/skins/moono-lisa/editor.css?t=GB8C

would be not found because of the - in the moono-lisa folder. I observe that this - needs to be converted to _ in order for the resource to be found, but - in the filename segment is ok and should not be changed to _ only folder segments need - changed to _

I solved it in my project by implementing a [custom IFileProvider](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Web.Common/Components/EmbeddedFileResolvingProvider.cs) by copying and modifying the existing EmbeddedFileProvider.

I don't know if this would be considered a bug or not, feel free to close this if you don't see it that way, but I thought I should report it.

I know the problem could be avoided by not using - in the embedded resource folders but in my case I'm embedding some 3rd party javascript and css that have - in some folder names and I don't want to modify the 3rd party resources, I just want them to work as is.

In my solution I first find out which part of the path is the filename because I don't want to replace - in the file name, but in the path before the file name I replace - with _ and that solves the problem.

**Comment by natemcmaster** [comment] 2017-06-12 20:37
It's a known issue with this file provider. Closing as a duplicate of https://github.com/aspnet/FileSystem/issues/184.

**Closed by natemcmaster** 2017-06-12 20:37 UTC
