### ISSUE TITLE
EmbeddedFileProvider does not support all file paths

### ISSUE THREAD

**Issue by JosVerburg** [aspnet/FileSystem#269] opened 2017-04-05 15:02 UTC
Hello,

We encountered some issues when using the `EmbeddedFileProvider`.

We use files which are placed in a directory with spaces, dashes, dots, and numbers e.g. `dir -..123`. After some testing we found out the manifest resource name is `dir__.._123`.
The unsupported cases are:
* ' ' should become a '_'
* '-' should become a '_'
* '.' followed by an integer should be postfixed with a '_'
These cases only apply to directory path parts, the filename stays the same e.g. `file -..123.txt` will still be `file -..123.txt`.

Another case we encountered was when having a parent path selector '..' in the middle of the path passed to the `EmbeddedFileProvider` e.g. `dir\\..\\dir`.

I've set up repository which reproduces the cases [https://github.com/JosVerburg/UnsupportedEmbeddedFileNames](https://github.com/JosVerburg/UnsupportedEmbeddedFileNames).

We'd be happy to create a PR for this since we've already supported these cases in our projects.

Greetings,
Jos Verburg

**Comment by natemcmaster** [comment] 2017-04-05 19:04
This issue was raised before on https://github.com/aspnet/FileSystem/issues/184. I would advise not rushing to make a PR yet. Not trying to be mean; I just want to save you time. There is a considerable amount of unresolved design discussion on this issue and we aren't ready yet to make big changes to this behavior (see https://github.com/aspnet/FileSystem/issues/184#issuecomment-288156871).

Closing as a duplicate of #184

**Closed by natemcmaster** 2017-04-05 19:04 UTC
Labels: duplicate
