### ISSUE TITLE
fileSystemWatcher has reached the maximum nunmber of files to watch.

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/FileSystem#167] opened 2016-02-27 21:44 UTC
There's a test failure on OSX https://travis-ci.org/aspnet/FileSystem/jobs/112301161

```
 Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenIsSameForSamePathCaseInsensitive [FAIL]
      System.IO.IOException : kqueue() FileSystemWatcher has reached the maximum nunmber of files to watch.
      Stack Trace:
          at System.IO.KqueueMonitor.Add (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>:0 
          at System.IO.KqueueMonitor.Scan (System.String path, Boolean postEvents, System.Collections.Generic.List`1& fds) [0x00000] in <filename unknown>:0 
          at System.IO.KqueueMonitor.Setup () [0x00000] in <filename unknown>:0 
          at System.IO.KqueueMonitor.DoMonitor () [0x00000] in <filename unknown>:0 
```

**Comment by muratg** [comment] 2016-02-29 06:34
Is this a CoreFX issue? Should we file a bug there instead?

**Comment by muratg** [comment] 2016-02-29 06:35
cc @joshfree

**Comment by joshfree** [comment] 2016-02-29 19:01
@sokket can you take a look?

**Comment by sokket** [comment] 2016-02-29 19:33
@victorhurdugaci How many files / folders are being created in this test? If you run this command you can see the maximum number that is allowed by the system in total:

```cat /proc/sys/fs/inotify/max_user_watches```

This exception is thrown when the FSW attempts to exceed this limit

**Comment by muratg** [comment] 2016-02-29 21:41
@cesarbs Could you have a look? If we're exceeding the max_user_watches value, we probably will need to change the tests.

**Comment by cesarbs** [comment] 2016-03-02 05:13
@sokket `/proc` is only available on Linux, no? I don't see that in OSX. Where can I find the same info on OSX?

I can't repro this on my Mac. @victorhurdugaci Are you seeing the failure consistently?

**Comment by cesarbs** [comment] 2016-03-02 05:15
@JunTaoLuo Is this https://github.com/aspnet/FileSystem/commit/ae5340aa9eb37cb5b452ebfe09a19d171607db97 related to this issue?

**Comment by JunTaoLuo** [comment] 2016-03-02 05:44
Yes adding that environment variable resolved the errors on travis. Related issue: https://github.com/aspnet/Mvc/issues/2348

**Comment by muratg** [comment] 2016-03-02 16:43
@sokket What's the corresponding setting on OS X?

Or could there be a different reason on OS X for this exception?

**Comment by sokket** [comment] 2016-03-02 18:07
OS X doesn't have this limitation due to fundamental differences between the FileSystemWatcher on Linux and OSX. On OS X, we have an OS API that watches the root folder and notifies us of any changes in the folder hierarchy; unfortunately, that doesn't exist in Linux. The Linux kernel only provides the inotify interface, which requires a watch handle for every single directory under the root watch directory, meaning there is an upper limit which I believe you are hitting.

**Comment by muratg** [comment] 2016-03-02 23:29
@cesarbs Can you check the Travis logs and see if we need to change the test cases?

**Comment by cesarbs** [comment] 2016-03-04 00:58
@sokket But @victorhurdugaci saw the exception on OSX. So there must be some kind of limitation.

@JunTaoLuo's change seems to do the trick. If we continue to see such errors we should disable parallel test runs. But I don't think the number of watchers created by the tests (even if a lot of them run in parallel) would come close to reaching the limit. We don't have any tests that create a large number of files.

Closing.

**Closed by cesarbs** 2016-03-04 00:58 UTC
Labels: investigate

**Comment by JunTaoLuo** [comment] 2016-03-04 01:06
The fix I made is a fix for mono and their watcher. This is not really an issue caused by us.
