### ISSUE TITLE
[Question] - IFileProvider, IFileInfo.PhysicalPath and Request Path

### ISSUE THREAD

**Issue by Tratcher** [aspnet/FileSystem#166] opened 2016-02-19 15:50 UTC
_From @dazinator on February 19, 2016 15:4_

Hi People :)
I have a question about how to get the "Request Path" for a file `IFileInfo`.

The scenario is that I have a `CompositeFileProvider` that contains a bunch of physical file providers, that point to various "webroot" directories from which I allow files to be served.

The structure looks like this:

```
wwwroot <-- my main web root (PhysicalFileProvider)
approot / packages / moduleA / wwwroot / ModuleA <-- module A web root (PhysicalFileProvider)
approot / packages / moduleB / wwwroot / ModuleB <-- module B web root (PhysicalFileProvider)
```

I am passing this Composite FileProvider to the `StaticFiles` Middleware, so that it can serve up:

```
~/main.js <-- some js file directly in the main wwwroot.
~/ModuleA/main.js <-- some js file in ModuleA's wwwroot/ModuleA folder.
~/ModuleB/main.js <-- some js file in ModuleB's wwwroot/ModuleB folder.
```

This is working nicely, but now I am puzzled. Given some `IFileInfo` from an `IFileProvider` i'd like to get back the appropriate Request Path.

So for example, if I grab some file:

```
 IFileProvider compositeFileProvider = GetFileProvider();
 var directoryContents = compositeFileProvider.GetDirectoryContents(folder);
 IFileInfo someFile = directoryContents.First();
```

The full physical path of that file could be: `C:\Website\approot\packages\ModuleA\wwwroot\ModuleA\main.js`

Of for example it could be:
`C:\Website\wwwroot\main.js`

How do I get the "Request Path" for that file?

So for `C:\Website\approot\packages\ModuleA\wwwroot\ModuleA\main.js` I want to get `/ModuleA/main.js`

and for `C:\Website\wwwroot\main.js` I want to get `main.js`

i.e  Is there some mechanism already provided by the framework for this kind of thing? I am hoping I don't have to write a whole bunch of reflection (as I am working at the `IFileProvider` level of abstraction) to get the particular file's `PhysicalFileProvider`, handling Composite file providers and all sorts, and then attempting to access the "PhysicalFileProvider.Root" to use that to try and do the mapping?

_Copied from original issue: aspnet/Hosting#610_

**Comment by Tratcher** [comment] 2016-02-19 15:50
No, there is no reverse lookup mechanic.

**Comment by dazinator** [comment] 2016-02-19 15:58
Hmm.. Seems like being able to get a Request Path for a particular file from the file system should be supported in the framework?

**Comment by dazinator** [comment] 2016-02-19 16:00
To be honest I'm not sure where support for this needs to go, perhaps in the StaticFilesMiddleware? but it just seems it should be somewhere! haha

**Comment by pranavkm** [comment] 2016-02-19 16:14
Sounds like you need the values computed here - https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/StaticFileMiddleware.cs#L72.

**Comment by dazinator** [comment] 2016-02-19 17:13
@pranavkm - I don't really think so, I think it's more of an API issue with the current `IFileProvider` or IFileInfo abstraction, i'll try and explain.

I don't think the Static Files Middleware needs to provide or hang on to mapped values in order to provide this context to me for a reverse lookup. Looking at the code this is basically my understanding of what's happening:

1. Static Files Middleware is given a "path" (request path) to serve static files on. e.g "~/MyFiles"
2. Static Files Middleware is give an "IFileProvider" to get files based on a "subpath".
3. When a request comes in, Static Files Middleware works out what the "subpath" of the file being requested is, by subtracting the "path" segment from the URL that it has been asked to serve files on (as per 1). 

The `IFileProvider` accepts the subpath from the middleware, and matches that to a File somewhere, like an embedded file, or a physical file etc. This `IFileProvider` could be a composite, in which case files can come from multiple sources.

The reason files can be matched by the `IFileProvider` on a "subpath" is because each `IFileProvider` is encapsulating a crucial bit of information needed for the mapping process - and that's a "root" path, from which it will match "subpaths" to actual files somewhere.

A `PhysicalFileProvider` can be instantiated with some folder as it's "root" directory, and an `EmbeddedFileProvider` can be instantiated with a base `Namespace` as its root..

This whole process works very easily, _in one direction _ (a Request Path, to a Physical Path) as the StaticFilesMiddleware is demonstrating in this code.

But it should also be possible for it work very easily, in the opposite direction - but due to the current API's of the classes involved, it does not. 

In order to map back in this other direction, we need these crucial pieces of information:

1. The "Subpath" of the file. This can be computed from:
    1. The Physical File Path of the file in question (IFileInfo)
    2. The "root" directory encapsulated by the `IFileProvider`
2. An (optional) path to append the Request Path of the file to, i.e if you are serving all files on '~/MyFiles' and the RequestPath of the file as per 1 and 2 is "/SomeFolder/somefile.js", then this argument would be the "MyFiles" that you want to prefix the Request Path with. This is the same argument that gets passed to the StaticFilesMiddleware as a "base" path to serve static files on.

So the main problem currently in going back in this other direction is that `IFileProvider` and `IFileInfo` don't provide the means to get the File's "SubPath".

**Comment by Tratcher** [comment] 2016-02-19 17:27
A few notes:
- IFileInfo is immutable. A file provider may have a static list of IFileInfo instances that it keeps giving out rather than creating one per request.
- In a complex file provider there may be multiple request paths mapped to a single IFileInfo. This prevents us from putting request path as a field on IFileInfo.
- As you pointed out, there's an additional component of the request path removed by the static file middleware that the file provider never knows about.
- There may have been other path rewriting that has taken place such that the request path given to static files is not the original value submitted by the client. E.g. the default files middleware rewrites the request path "/" as "/index.html".
- An IFileInfo may also be used as only one of several inputs into a response. E.g. A page may be composed from multiple static and dynamic components where the request path does not map to any individual resource, only the composite result.

All told IFileInfo is just a resource, it has no notion of how it was was selected and one cannot assume there's a one-to-one relationship between a request path and an IFileInfo.

**Comment by dazinator** [comment] 2016-02-19 18:10
@Tratcher 
> IFileInfo is immutable. A file provider may have a static list of IFileInfo instances that it keeps giving out rather than creating one per request.

> All told IFileInfo is just a resource, it has no notion of how it was was selected and one cannot assume there's a one-to-one relationship between a request path and an IFileInfo.

Just to clarify, wherever you have said Request Path, I am assuming that is the "sub path" argument that an `IFileProvider` requires: 

![image](https://cloud.githubusercontent.com/assets/3176632/13183602/942ebfda-d72f-11e5-94b7-9ab0198dd18f.png)

A few responses:

1. If it's a many to one association between a sub path, and an `IFileInfo`, the `IFileInfo` could expose an IEnumerable or an IList or some means to access it's subpaths.

2. If you would preder to keep IFileInfo dumb, `IFileProvider` has the "knowledge" of how to map a subpath to a particular file, so it must be in a great position to also take an `IFileInfo` and map back the other way to give a list of "sub paths".

> In a complex file provider there may be multiple request paths mapped to a single IFileInfo. This prevents us from putting request path as a field on IFileInfo.

Is there a concrete example of such a provider just out of curiosity?

> There may have been other path rewriting that has taken place such that the request path given to static files is not the original value submitted by the client. E.g. the default files middleware rewrites the request path "/" as "/index.html".

This means when we map back the other way we should get "/index.html" which is what I want so not sure I see a problem here. We aren't after the original Request URL that the client sent, just a valid Request URL for the particular file in question. A URL re-writer will often re-write invalid url's to point to some resource (like an 404 page or whatever) and ultimately if the 404 page is the file, then its the Request URL of that file that I am trying to obtain here not the original invalid url.

**Comment by lodejard** [comment] 2016-02-19 18:53
File providers are also intended to be able to be wrapped in a decorator pattern where the decorator can alter the path parameter being passed down. For that reason you need to assume the resulting IFileInfo will never have correct knowledge of the original path argument.

**Comment by davidfowl** [comment] 2016-02-19 19:11
@dazinator You'll need to wrap the FileProvider with your own that preserves the path.

**Comment by dazinator** [comment] 2016-02-19 19:13
@lodejard sounds complicated! At the present time, I'm having to inspect each IFileProvider and try and access the root path. From their I can subtract that from the "PhysicalPath" of any of it's IFileInfo's to get that 'IFileInfo's` subpath. I can then use that subpath when formulating the URL. Any reason's why this approach wouldn't work? Would this decorator interfere with this to potentially through of the results? 

The fact this is soo dificult is telling me I am attempting to so something that has never been done before. Has no-one ever needed to get the Request path for a physical file before? What should I be doing instead? Welcome to take pointers!

**Comment by dazinator** [comment] 2016-02-19 19:16
@davidfowl - thanks, so - wrap the `IFileProvider` (which is most likely going to be a composite file provider at runtime) with my own, and each time a File is requested, record the path. Then on my own file provider, add some method to give me that information back for some arbitrary `IFileInfo` object?

Hmm. ok cheers David - I'll give that a try!

**Comment by lodejard** [comment] 2016-02-19 19:20
Only the code which made the original call has the original path. There is no guarantee that the IFileProvider which creating the resulting IFileInfo was actually given the correct original path. This is by design - because IFileProviders are intended to be used as decorator patterns where they may actually be altering the path they pass to the inner provider.

Does that make sense? It's not just a matter of adding a FullPath property to the IFileInfo - it's a actually literally impossible for the returned object to know the original full path.

People do this, it's not new, but if you have a system which needs to know both the original request path and have an IFileInfo you pass them both as two arguments. Or you use the request path on the http context if you have access to the http context and don't want to pass original path in addition.

**Comment by dazinator** [comment] 2016-02-19 19:29
@lodejard  ok, so basically, `IFileProviders` offer a one way mapping of a subpath to an `IFileInfo` and it's a literal impossibility to map back the other way, from an IFileInfo, to get subpath information, even if you have access to the top level `IFileProvider` ? Is this the way things will stay?
And therefore the only solution to my problem at present is @davidfowl's suggestion of creating a new top level, wrapping IFileProvider, that caches the subpaths for requested files, and thus can provide a method to do a reverse lookup?
Please correct me if I am off base with any of that, it has been a long day :)

**Comment by Tratcher** [comment] 2016-02-19 19:39
@dazinator you never said what you were going to do with the value. What's your end-to-end scenario?

**Comment by dazinator** [comment] 2016-02-22 14:59
@Tratcher 

Sure. I have avoided getting too much into my own specific scenario, because it's fairly complicated, but I think there is in my view a simpler use case which perhaps you wouldn't mind if I present that first? 

	1. Being able to render a hyperlink to download some files available through an IFileProvider.

So for example, if the application stores content in some folders outside of `IHostingEnvironment.WebRoot` and wants to display a page where those files can be downloaded. 

The current mechanism to do this (correct me if I am wrong) would be to:

1. Create a `PhysicalFileProvider`s (wrapped by a composite) for those external folder locations.
2. Register the CompositeFileProvider as the `IHostingEnvironment.WebRootFileProvider` (or as a file provider with the `StaticFiles` middleware.

With those tasks accomplished, you can download those files _if you know the url request path in advance_ so that you can type it in the browser, it will be resolved and the file will be served. But how could you display a page where it would list those files, with an appropriate download link?  

This is not precisely what my use case is, but it demonstartes the same problem.

**Comment by dazinator** [comment] 2016-02-22 15:06
As an aside, I have now managed to work around my own use case, by using a convention to work out what the root path is of a `IFileInfo` and therfore can calculate the subpath - although its not perfect its a good enough heuristic.

I am working to the limitation that I only want to serve physical files, (Physical File Provider) and that the root path of my `PhysicalFileProvider`s will always be set to a "wwwroot" directory.

Therefore to calculate the "subpath" of a particular `IFileInfo" I can substring the `PhysicalPath` from the index of the "wwwroot"  - so everything that follows "wwwroot" I consider to be the subpath fo the file. This then allows me to formulate a Request path like: "~/somefolder/myfile.js"

If i'm serving static files on "~/somepath" then I obvioulsy take that "somepath" into account such that the request path I build ends up being: "~/somepath/somefolder/myfile.js"

However this logic is not perfect, as it relies upon a convention and a heuristic, and won't currently work for `EmbeddedFileProvider`s. 

So it will still be nice if you guys could provide a better mechanic for this kind of thing.

**Comment by lodejard** [comment] 2016-02-25 19:12
it sounds like what you're describing is: given an `IFileInfo` what is the path you would pass to an `IFileProvider.GetFile(string path)` in the future to get the same instance.

Because this scenario starts with "given an `IFileInfo`" that must have been returned by a call to the root `IFileProvider`. Why not preserve that path? Instead of having IFileInfo, have an `KeyValuePair<string, IFileInfo>`, or a tuple of `Tuple<string, IFileInfo>`, or even a `public class FileAndPath {public string Path {get;set;} public IFileInfo {get;set;}}`

If on the other hand you're saying you don't actually start with an `IFileInfo` and you are saying you start with only the physical path, what virtual path would give you an IFileInfo to that physical path - the system's just not designed for that. 

Like @Tratcher said - just like in ASP.NET 4.x - the MapPath for virtual-to-physical mapping does not have a reverse.

**Comment by dazinator** [comment] 2016-02-25 20:54
@lodejard 
> it sounds like what you're describing is: given an IFileInfo what is the path you would pass to an IFileProvider.GetFile(string path) in the future to get the same instance.

Yep spot on!

> Because this scenario starts with "given an IFileInfo" that must have been returned by a call to the root IFileProvider. Why not preserve that path?


Because the IFileProvider i am working with is actually a composite one created by the application at startup so it doesnt have a single "root" to preserve. At the moment different "modules" (my application is extensible)  can add their own IFileProviders to this composite during app startup, in order to include plugin / module specific directories. All my app sees is the composite and I dont want to have to break the IFileProvider abstraction in order to work out if its a composite and gather the individual roots by iterating and typecasting.

Given that each implementation of an IFileProvider encapsulates a root - why can't this be exposed by the IFileProvider abstraction? Would there ever be an IFileProvider implementation without a root given that it works with "subpaths?" I doubt it, and if there was then IFileProvider.Root could just expose an empty string.

As it stands I'm going to have to create my own layer of IFileProviders just to try and preserve the roots - and that means creating a new FileProvider for each available file provider type, (composite, embedded, physical) and any more that are written in future.

**Comment by lodejard** [comment] 2016-02-26 04:11
```cs
public static class MyFileProviderExtensions
{
  public static KeyValuePair<string, IFileInfo> GetFileAndPath(
    this IFileProvider provider, 
    string path)
  {
    return new KeyValuePair<string, IFileInfo>(
      path, 
      provider.getFile(path));
  }
}

// usage
var yep = theProvider.GetFileAndPath(thePath);
```
:)

**Comment by Tratcher** [comment] 2016-03-02 20:53
If you want to enumerate all the paths then you could walk the directory structure starting at the base url ("/") and call IFileProvider.GetDirectoryContents recursively, building up the urls using IFileInfo.Name.

**Comment by dazinator** [comment] 2016-05-23 16:03
@Tratcher @lodejard - thanks both. This is indeed what I ended up doing. Happy for you to close this issue.

**Comment by dazinator** [comment] 2016-05-23 16:20
And here is an extension method that uses recursion as suggested to build up the list of files with subpath information:

```

 public static class FileProviderExtensions
    {
        public static IDictionary<string, IFileInfo> GetAllFiles(this IFileProvider provider)
        {
            var results = new Dictionary<string, IFileInfo>();
            GetAllFilesFromDirectory(provider, results, "/");
            return results;
        }

        public static void GetAllFilesFromDirectory(this IFileProvider provider, Dictionary<string, IFileInfo> files, string dirPath = "/")
        {
            var dirContents = provider.GetDirectoryContents(dirPath);
            if (dirContents.Exists)
            {
                foreach (var dirEntry in dirContents)
                {
                    if (dirEntry.Exists)
                    {
                        var subPath = string.Format("{0}{1}", dirPath, dirEntry.Name);
                        if (dirEntry.IsDirectory)
                        {
                            var nextPath = string.Format("{0}/", subPath);
                            GetAllFilesFromDirectory(provider, files, nextPath);
                        }
                        else
                        {
                            files.Add(subPath, dirEntry);
                        }
                    }
                }
            }
        }
    }

```

**Comment by muratg** [comment] 2017-05-12 21:52
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 21:52 UTC
